apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ddhub-client-gateway-api.fullname" . }}-configmap
  labels:
    {{- include "ddhub-client-gateway-api.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.clientgateway.config.port | quote }}
  WEBSOCKET: {{ .Values.clientgateway.config.websocket | quote }}
  WEBSOCKET_URL: {{ .Values.clientgateway.config.websocket_url | quote }}
  WEBSOCKET_PROTOCOL: {{ .Values.clientgateway.config.websocket_protocol | quote }}
  WEBSOCKET_RECONNECT: {{ .Values.clientgateway.config.websocket_reconnect | quote }}
  WEBSOCKET_RECONNECT_TIMEOUT: {{ .Values.clientgateway.config.websocket_reconnect_timeout | quote }}
  WEBSOCKET_RECONNECT_MAX_RETRIES: {{ .Values.clientgateway.config.websocket_reconnect_max_retries | quote }}
  EVENTS_EMIT_MODE: {{ .Values.clientgateway.config.events_emit_mode | quote }}
  DSB_BASE_URL: {{ .Values.clientgateway.config.dsb_base_url | quote }}
  CHAIN_ID: {{ .Values.clientgateway.config.chain_id | quote }}
  RPC_URL: {{ .Values.clientgateway.config.rpc_url | quote }}
  CACHE_SERVER_URL: {{ .Values.clientgateway.config.cache_server_url | quote }}
  EVENT_SERVER_URL: {{ .Values.clientgateway.config.event_server_url | quote }}
  PARENT_NAMESPACE: {{ .Values.clientgateway.config.parent_namespace | quote }}
  SECRETS_ENGINE: {{ .Values.clientgateway.config.secret_engine | quote }}
  VAULT_ENDPOINT: {{ .Values.clientgateway.config.vault_endpoint | quote }}
  NODE_ENV: {{ .Values.clientgateway.config.node_env | quote }}