apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dsb-client-gateway.fullname" . }}-configmap
  labels:
    {{- include "dsb-client-gateway.labels" . | nindent 4 }}
data:
  messagebrokerPort: {{ .Values.clientgateway.config.port | default "3000" | quote }}
  natsUrl: {{ .Values.clientgateway.config.natsClusterUrl | default "nats://nats.default.svc:4222" | quote }}