{{- if .Values.clientgateway.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ddhub-client-gateway-api.fullname" . }}-ui
  labels:
    {{- include "ddhub-client-gateway-api.ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.clientgateway.ui.service.type }}
  ports:
    - port: {{ .Values.clientgateway.ui.service.port }}
      targetPort: {{ .Values.clientgateway.ui.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "ddhub-client-gateway-api.ui.selectorLabels" . | nindent 4 }}
{{- end }}