{{- if .Values.clientgateway.ui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ddhub-client-gateway-api.fullname" . }}-ui
  labels:
    {{- include "ddhub-client-gateway-api.ui.labels" . | nindent 4 }}
spec:
  {{- if not .Values.clientgateway.ui.autoscaling.enabled }}
  replicas: {{ .Values.clientgateway.ui.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ddhub-client-gateway-api.ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.clientgateway.ui.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ddhub-client-gateway-api.ui.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ddhub-client-gateway-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-ui
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.clientgateway.ui.image.repository }}:{{ .Values.clientgateway.ui.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.clientgateway.ui.image.pullPolicy }}
          resources:
            {{- toYaml .Values.clientgateway.ui.resources | nindent 12 }}
          {{- if .Values.clientgateway.ui.probes.liveness }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          {{- end }}
          {{- if .Values.clientgateway.ui.probes.readiness }}
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}