apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dsb-client-gateway.fullname" . }}
  labels:
    {{- include "dsb-client-gateway.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dsb-client-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dsb-client-gateway.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dsb-client-gateway.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.clientgateway.config.port | default 3000 }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dsb-client-gateway.fullname" . }}-configmap
                  key: PORT
            - name: WEBSOCKET
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dsb-client-gateway.fullname" . }}-configmap
                  key: WEBSOCKET
            - name: WEBSOCKET_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dsb-client-gateway.fullname" . }}-configmap
                  key: WEBSOCKET_URL
            - name: WEBSOCKET_RECONNECT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dsb-client-gateway.fullname" . }}-configmap
                  key: WEBSOCKET_RECONNECT
            - name: WEBSOCKET_RECONNECT_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dsb-client-gateway.fullname" . }}-configmap
                  key: WEBSOCKET_RECONNECT_TIMEOUT
            - name: WEBSOCKET_RECONNECT_MAX_RETRIES
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dsb-client-gateway.fullname" . }}-configmap
                  key: WEBSOCKET_RECONNECT_MAX_RETRIES
            - name: EVENTS_EMIT_MODE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dsb-client-gateway.fullname" . }}-configmap
                  key: EVENTS_EMIT_MODE
            - name: EVENTS_MAX_PER_SECOND
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dsb-client-gateway.fullname" . }}-configmap
                  key: EVENTS_MAX_PER_SECOND
            - name: DSB_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dsb-client-gateway.fullname" . }}-configmap
                  key: DSB_BASE_URL
            - name: DSB_CONTROLLABLE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dsb-client-gateway.fullname" . }}-configmap
                  key: DSB_CONTROLLABLE
            - name: DSB_PM2_PROCESS_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dsb-client-gateway.fullname" . }}-configmap
                  key: DSB_PM2_PROCESS_NAME
            - name: DSB_BIN_PATH
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dsb-client-gateway.fullname" . }}-configmap
                  key: DSB_BIN_PATH
            - name: IN_MEMORY_DB_FILENAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dsb-client-gateway.fullname" . }}-configmap
                  key: IN_MEMORY_DB_FILENAME
            - name: CHAIN_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dsb-client-gateway.fullname" . }}-configmap
                  key: CHAIN_ID
            - name: RPC_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dsb-client-gateway.fullname" . }}-configmap
                  key: RPC_URL
            - name: CACHE_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dsb-client-gateway.fullname" . }}-configmap
                  key: CACHE_SERVER_URL
            - name: EVENT_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dsb-client-gateway.fullname" . }}-configmap
                  key: EVENT_SERVER_URL
            - name: PARENT_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dsb-client-gateway.fullname" . }}-configmap
                  key: PARENT_NAMESPACE
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
